### ISSUE TITLE
игра не заканчивается

### ISSUE THREAD

**Issue by neymanushka** [Helena-Bali/Minesweeper#1]
после полного разминирования игра не заканчивается:
![изображение](https://user-images.githubusercontent.com/5113973/232037883-ccb06ef2-555b-43b5-a0d5-d40741567ff1.png)

**Comment by Helena-Bali** [comment]
Здравствуйте, у вас 41 флажок, это не полное разминирование.
![неполное разминирование](https://user-images.githubusercontent.com/68009499/232472206-50f757d6-cc92-4213-9cfa-8595b6e9c5f5.png)

**Comment by Helena-Bali** [comment]
Вот так выглядит полное разминирование, всего 40 бомб, должно быть 40 флажков. У вас вокруг цифры "2" 3 флажка. Очевидно, что около цифры 2 должно быть 2 бомбы, а не 3.
![полное разминирование](https://user-images.githubusercontent.com/68009499/232473173-3889d084-1e97-485b-891f-237e73f4248f.png)

**Comment by neymanushka** [comment]
точно! my bad, sorry.
